### ISSUE TITLE
Cant upload delivery address

### ISSUE THREAD

**Issue by jc4balos** [Elleined/marketplace-api#10]
![image](https://github.com/Elleined/marketplace-api/assets/66464582/b813d70e-9f37-46a2-bc45-5a3a8edc15ed)
![image](https://github.com/Elleined/marketplace-api/assets/66464582/504881de-6a52-4c8e-b94b-a53372c6d404)
![image](https://github.com/Elleined/marketplace-api/assets/66464582/6c41ee6d-4bb3-48a5-889d-4c21defb5ddb)

already did clean compile in maven and workspace cache clean

**Comment by jc4balos** [comment]
@Elleined still doesnt work

**Comment by jc4balos** [comment]
### Step by step procedure I did when running the app

1. Run MarketplaceApplication 

![image](https://github.com/Elleined/marketplace-api/assets/66464582/e1a68ce5-6404-4ccd-bbfb-19dc22a2feff)

2. Run ForumApplication

![image](https://github.com/Elleined/marketplace-api/assets/66464582/fb9d89a3-6136-42c4-a713-0105a1fc98b6)

3. EmailSenderApplication.java encountered an error when running (The code will still run with the error)
![image](https://github.com/Elleined/marketplace-api/assets/66464582/94d35288-1a7b-49da-9128-c5cb83bd6331)
![image](https://github.com/Elleined/marketplace-api/assets/66464582/4d23bfea-0135-4a77-b1fb-a54d6a65a0a3)

4. Run MarketplaceAPI and build will fail (The code can still run with the error)
![image](https://github.com/Elleined/marketplace-api/assets/66464582/dab1cbdc-e954-4b44-983f-fedc3238970d)
![image](https://github.com/Elleined/marketplace-api/assets/66464582/ed437ea6-1bba-4eb3-984a-5fe29d29582d)

5. Run Location API
![image](https://github.com/Elleined/marketplace-api/assets/66464582/73ff2285-2751-410c-8ab7-624ee7918dad)

6. Log in
![image](https://github.com/Elleined/marketplace-api/assets/66464582/acc99fd5-a88f-4d67-b962-b13910066955)
_logged in using cardodalisay_

7. adding delivery address
![image](https://github.com/Elleined/marketplace-api/assets/66464582/acb2e602-5a7d-40bf-b771-e45ac94b728c)

8. undefined upon saving
![image](https://github.com/Elleined/marketplace-api/assets/66464582/02c55c26-12e2-4be5-8f4a-6610fb06405f)

now we get error500
![image](https://github.com/Elleined/marketplace-api/assets/66464582/d5c29806-576e-45e8-9292-9277b20ed5c6)
`
java.lang.Error: Unresolved compilation problem:
        DELIVERY_ADDRESS_LIMIT cannot be resolved to a variable

        at com.elleined.marketplaceapi.model.user.User.hasReachedDeliveryAddressLimit(User.java:133) ~[classes/:na]
        at com.elleined.marketplaceapi.service.address.AddressServiceImpl.saveDeliveryAddress(AddressServiceImpl.java:38) ~[classes/:na]     
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.11.jar:6.0.11]        
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.11.jar:6.0.11]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.11.jar:6.0.11]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756) ~[spring-aop-6.0.11.jar:6.0.11]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.11.jar:6.0.11]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.11.jar:6.0.11]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.11.jar:6.0.11]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.11.jar:6.0.11]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756) ~[spring-aop-6.0.11.jar:6.0.11]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-6.0.11.jar:6.0.11]
        at com.elleined.marketplaceapi.service.address.AddressServiceImpl$$SpringCGLIB$$0.saveDeliveryAddress(<generated>) ~[classes/:na]    
        at com.elleined.marketplaceapi.controller.UserController.saveDeliveryAddress(UserController.java:109) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.11.jar:6.0.11]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.11.jar:6.0.11]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.11.jar:6.0.11]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.11.jar:6.0.11]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.11.jar:6.0.11]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.11.jar:6.0.11]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.11.jar:6.0.11]      
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.11.jar:6.0.11]        
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.11.jar:6.0.11]    
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.11.jar:6.0.11]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.11.jar:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.11.jar:6.0.11]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.11.jar:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.11.jar:6.0.11]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]       
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.11.jar:6.0.11]      
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]       
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.11.jar:6.0.11]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]       
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.11.jar:10.1.11]      
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.11.jar:10.1.11]       
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.11.jar:10.1.11]   
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.11.jar:10.1.11]  
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.11.jar:10.1.11]      
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.11.jar:10.1.11]        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.11.jar:10.1.11]       
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
`


**Doing it in postman will lead to same error**
![image](https://github.com/Elleined/marketplace-api/assets/66464582/90d3d69e-4739-4286-9052-dfd4a4a3a3a8)


### Steps in resolving the issue
1. tried to declare the` deliveryAddressLimit `on `AddressServiceImpl.java`

`package com.elleined.marketplaceapi.service.address;

// Import statements

@Slf4j
@RequiredArgsConstructor
@Service
@Transactional
public class AddressServiceImpl implements AddressService {

    // Define the DELIVERY_ADDRESS_LIMIT constant
    private static final int DELIVERY_ADDRESS_LIMIT = 5;

    // Other class members

    @Override
    public DeliveryAddress saveDeliveryAddress(User orderingUser, DeliveryAddressDTO deliveryAddressDTO) throws DeliveryAddressLimitException {
        if (orderingUser.hasReachedDeliveryAddressLimit()) {
            throw new DeliveryAddressLimitException("Cannot save another delivery address! Because you already reached the limit which is " + DELIVERY_ADDRESS_LIMIT);
        }

        // Rest of the method
    }

    // Other methods

}
`

**now  the error is gone but you will recieve this message**
![image](https://github.com/Elleined/marketplace-api/assets/66464582/bf041a90-729d-4165-9ff7-be2e32b57ed2)
_P.S.: I just set the deliveryAddressLimit variable to 10 just to test things_

### My insights
Fixing the logic here might help to fix the problem
![image](https://github.com/Elleined/marketplace-api/assets/66464582/30cc2e46-1552-423e-a787-55804e40a1f4)
_PS: tried to manipulate some things if it will work_

**Optimizing the code will solve the problem**
**A similar approach might also solve the problem on emailSenderAPI**

**Comment by Elleined** [comment]
- I try hitting the max delivery address and its fine

# Possible solution
- I already changed the way the delivery address limit is imported. HOPE it works if not proceed to second suggestion.

- Maybe opening the project in one folder affects that because its suppose to be opned in separate project for each api
and spring cant find the delivery_address_limit import because it starting to find the variable from the root folder which is not really available. spring automatically scan the package from the root thats why when you ready to use the address limit it cant find that variable. TRY RUNNING EACH PROJECT SEPARATELY.

- Also in the rejactored method saveDeliveryAddress if else are not necessary cause the throw exception will automatically cut off the method execution the moment its been triggered.

<img width="960" alt="image" src="https://github.com/Elleined/marketplace-api/assets/111877930/46b2c206-8a49-49a4-9170-f1c0e98b607e">
